import Head from 'next/head'
import Top from '@/components/Top'
import Mid from '@/components/Mid'
import { useEffect, useState } from 'react';
import { motion } from "framer-motion";
import { CustomCursor } from "react-svg-cursor";


export default function Home() {

  function handleMO(e) {
    //in here, handle e.clientX and pass it to the animation

    const pos = {
      x: e.clientX - 50,
      y: e.clientY - 60
    };

    setLineData(dataGenerator(linenum, lineSize, spc, pos));
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="bg-black text-white h-fit snap snap-y snap-mandatory overflow-x-hidden">
        <div className="snap-center">
          <Top />
        </div>

        <div className="snap-center">
          <Mid />
        </div>
        <CustomCursor
          component={'nextjs'}
          isDisabled={false}
          width={80}
          height={80}
          transform="translate(-28px, -50px) scale(-1, 1) rotateZ(0deg) "
        />
      </main>
    </>
  )
}
