import Head from 'next/head'
import Top from '@/components/Top'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="bg-black text-white h-screen w-screen">
        <Top />
      </main>
    </>
  )
}
