create table
  public.projects (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name character varying not null,
    description text null,
    link character varying null,
    team_code character varying null,
    constraint projects_pkey primary key (id),
    constraint projects_team_code_fkey foreign key (team_code) references teams (code)
  ) tablespace pg_default;
