create table
  public.participants (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name character varying null,
    email character varying not null,
    age smallint null,
    mobile character varying null,
    university character varying null,
    course character varying null,
    vegan boolean null default false,
    notes text null,
    confirmation text null,
    constraint participants_pkey primary key (id, email),
    constraint participants_confirmation_key unique (confirmation)
  ) tablespace pg_default;
